version: '3'
services:
  db:
    image: postgres:13-alpine
    container_name: postgresql
    build:
      dockerfile: ./postgres/Dockerfile
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    hostname: postgres
    user: root
    ports:
      - "5432:5432"